export const inforMap = {
    proName: "产品名称",
    proShop: "厂商",
    proLeval: "产品级别",
    proType: "产品类型",
    proRange: "续航里程",
    fastChargingtime: "快充时间",
    slowChargingtime: "慢充时间",
    maxPower: "最大功率",
    maxTorque: "最大扭矩",
    motor: "电机",
    dimensions: "长宽高",
    maxSpeed: "最高车速（km/h）",
    fuelTankapacity: "油箱容积",
    comprehensiveFuelconsumption: "WLTC综合油耗",
    acceleration: "官方0-100km/h加速",
    fuelConsumption: "电能当量燃料消耗值",
    vehicleWarranty: "车辆质保",
    length: "长度（mm）",
    width: "宽度（mm）",
    heigth: "高度（mm）",
    wheelbase: "轴距（mm）",
    frontTrackwidth: "前轮距（mm）",
    rearTrackwidth: "后轮距（mm）",
    groundclearanceMin: "满载最小离地间隙（mm）",
    approachAngle: "接近角（度）",
    departureAngle: "离去角（度）",
    maxGradeability: "最大爬坡度（度）",
    maxClimbingangle: "最大爬坡角",
    minTurningradius: "最小转弯半径",
    bodyStructure: "车身结构",
    openWay: "车门开启方式",
    doorSum: "车门数",
    seatSum: "座位数",
    trunkCapacity: "后备箱容积",
    dragCoefficient: "空气阻力系数",
    equipmentQuality: "装备质量（kg）",
    maxEquipmentquality: "最大满载质量（kg）",
    motorType: "电机类型",
    motorTotalpower: "电机总功率(k w)",
    motorTotaltorque: "电机总扭矩（N * m）",
    beMotorpower: "前电机最大功率(kw)",
    beMotortotaltorque: "前电机最大扭矩（N * m）",
    numCylinders: "气缸个数",
    fuelForm: "燃料形式",
    supplyMethod: "供油方式",
    headMaterial: "缸盖材料",
    bodyMaterial: "缸体材料",
    environmentalStandards: "环保标准",
    numGears: "变速箱挡位个数",
    typeGear: "变速箱类型",
    beTiresize: "前轮胎规格",
    aftTiresize: "后轮胎规格",
    displacement: "排量（L）",
    upTime: "上市时间",
    speedBox: "变速箱",
    addSpeedone: "官方0-100km/h加速(s)",
    addSpeedfive: "官方0-50km/h加速(s)",
    nedsOilall: "综合油耗（L/100km）",
    lowOilstatus: "最低荷电状态耗油（L/100km）",
    firstWarranty: "首任车主质保政策",
    engineModel: "发动机型号",
    engineLayout: "发动机布局",
    airIntakeform: "进气形式",
    cylinderArrangement: "气缸排列形式",
    numberOfcylinders: "气缸数(个)",
    compressionRatio: "压缩比",
    numOfvalvespercylinder: '每缸气门数(个)',
    valveTrain: "气门机构",
    cylinderDiameter: "缸径 (mm)",
    stroke: "行程 (mm)",
    maximumHorsepower: "最大马力 (Ps)",
    maxKw: "最大功率 (kW)",
    maxRpm: "最大功率转速 (r/min)",
    maxKwbh: "最大扭矩转速(Nm)",
    maxTorquespeed: "最大扭矩转速 (rpm)",
    engineSpecifictechnology: "发动机特有技术",
    fuelNum: "燃料标号",
    oilSupplymethod: "供油方式",
    cylinderHeadmaterial: "岗盖材料",
    cylinderMaterial: "缸体材料",
    maxWaterdeep: "最大涉水深度 (mm)",
    beCapacity: "前电机容量(kWh)",
    fuelTankcapacity: "油箱容积(L)",
    cargoVolume: "行李箱容积(L)",
    numberOftransmissiongears: "挡位个数",
    type: "变速箱类型",
    drivingMethod: "驱动方式",
    fourWheeldriveform: "四驱形式",
    centerDifferentialstructure: "中央差速器结构",

    // 车轮制动
    frontSuspensiontype: "前悬架类型",
    backSuspensiontype: "后悬架类型",
    typeOfassistance: "助力类型",
    vehicleBodystructure: "车体结构",
    frontBraketype: "前制动器类型",
    backBraketype: "后制动器类型",
    parkingBraketype: "驻车制动类型",
    frontTirespecifications: "前轮胎规格",
    backTirespecifications: "后轮胎规格",
    spareTirespecifications: "备胎规格",

    // 内部配置
    steeringWheelmaterial: "方向盘材质",
    wheelPositionadjustment: "方向盘位置调节",
    multifunctionSteeringwheel: "多功能方向盘",
    steeringWheelshifting: "方向盘换挡",
    steeringHot: "方向盘加热",
    steeringMemory: "方向盘记忆",
    computerDisplayscreen: "行车电脑显示屏",
    instrumentPanel: "仪表盘亮度调节",
    instrumentSize: "仪表盘尺寸",
    digitalDisplay: "全液晶仪表盘",
    dashCam: "行车记录仪",
    activeNoisereduction: "主动降噪",
    mobileChargingfunction: "手机无线充电功能",

    // 灯光配置
    lightSource: "近光灯光源",
    farLightsource: "远光灯光源",
    lightingFeatures: "灯光特色功能",
    daytimeRunninglights: "LED日间行车灯",
    adaptiveHighlowbeams: "自适应远近光",
    automaticHeadlights: "自动头灯",
    corneringLamp: "转向辅助灯",
    turnSignalheadlights: "转向头灯",
    frontFoglights: "前雾灯",
    headlightrainFogmode: "大灯雨雾模式",
    heightAdustable: "大灯高度可调",
    headlampCleaningdevice: "大灯清洗装置",
    delayedHeadlights: "延时关闭大灯",
    touchReadinglight: "触摸式阅读灯",
    ambientLighting: "车内环境氛围灯",

    // 多媒体配置
    controlColorscreen: "中控彩色液晶屏幕",
    controlColorscreensize: "中控彩色液晶屏幕尺寸",
    intelligentSystem: "车载智能系统",
    navigationSystem: "GPS导航系统",
    informationDisplay: "导航路况信息显示",
    roadRescuecall: "道路救援呼叫",
    bluetoothPhone: "蓝牙/车载电话",
    mobileMapping: "手机互联/映射",
    speechControlsystem: "语音识别控制系统",
    gesture: "手势控制",
    facialRecognition: "面部识别",
    internetVehicles: "车载互联网",
    otaUpgrade: "OTA升级",
    rearScreen: "后排液晶屏",
    rearControlmultimedia: "后排控制多媒体",
    chargingInterface: "多媒体/充电接口",
    numInterfaces: "USB/Type-C接口数量",
    carDvd: "车载CD/DVD",
    powerSupply: "220V/230V电源",
    bagPower: "行李厢12V电源接口",
    speakerBrandname: "扬声器品牌名称",
    speakerNum: "扬声器数量",

    // 空调冰箱
    temperatureControlmethod: "空调温度控制方式",
    airConditioning: "后排独立空调",
    airOutlet: "后座出风口",
    zoneControl: "温度分区控制",
    carAirpurifier: "车载空气净化器",
    insideVehicle: "车车内PM2.5过滤装置",
    negativeGenerator: "负离子发生器",
    interiorFragrance: "车内香氛装置",
    carRefrigerator: "车载冰箱",
    numUltrasonicradars: "超声波泊车雷达数量",
    numCameras: "倒车视频影像",

    // 主被动安全装备
    passengerSeatairbags: "主/副驾驶座安全气囊",
    frontRearsideairbags: "前/后排侧气囊",
    headAircurtains: "前/后排头部气囊(气帘)",
    kneeAirbag: "膝部气囊",
    passivePedestrianprotection: "被动式行人保护系统",
    tirePressuremonitoringfunction: "胎压监测装置",
    continueDrivingzerotirepressure: "零胎压继续行驶",
    seatbeltNotfastenedreminder: "安全带未系提示",
    childSeatinterface: "儿童座椅接口",
    antiLocksystem: "防抱死制动系统(ABS)",
    brakeForcedistribution: "刹车力分配(EBD/CBC等)",
    brakeAssist: "制动辅助(EBA/BAS/BA等)",
    tractionControl: "牵引力控制(ASR/TCS/TRC等)",
    bodyStabilitycontrol: "车身稳定控制(ESC/ESP/DSC等)",
    parallelAssistance: "并线辅助",
    laneDeparturewarningsystem: "车道偏离预警系统",
    carLinesys: "车道保持辅助系统",
    roadTrafficsignrecognition: '道路交通标识识别系统',
    activeSafetysystem: "主动刹车/主动安全系统",
    fatigueDrivingtips: "疲劳驾驶提示",
}


const xxx = {


}