export const inforMap = {
    proName: "产品名称",
    proShop: "厂商",
    proLeval: "产品级别",
    proType: "产品类型",
    proRange: "续航里程",
    fastChargingtime: "快充时间",
    slowChargingtime: "慢充时间",
    maxPower: "最大功率",
    maxTorque: "最大扭矩",
    motor: "电机",
    dimensions: "长宽高",
    maxSpeed: "最高车速（km/h）",
    fuelTankapacity: "油箱容积",
    comprehensiveFuelconsumption: "WLTC综合油耗",
    acceleration: "官方0-100km/h加速",
    fuelConsumption: "电能当量燃料消耗值",
    vehicleWarranty: "车辆质保",
    length: "长度",
    width: "宽度",
    heigth: "高度",
    wheelbase: "轴距",
    frontTrackwidth: "前轮距",
    rearTrackwidth: "后轮距",
    groundclearanceMin: "满载最小离地间隙",
    approachAngle: "接近角",
    departureAngle: "离去角",
    maxGradeability: "最大爬坡度",
    maxClimbingangle: "最大爬坡角",
    minTurningradius: "最小转弯半径",
    bodyStructure: "车身结构",
    openWay: "车门开启方式",
    doorSum: "车门数",
    seatSum: "座位数",
    trunkCapacity: "后备箱容积",
    dragCoefficient: "空气阻力系数",
    equipmentQuality: "装备质量（kg）",
    maxEquipmentquality: "最大满载质量（kg）",
    motorType: "电机类型",
    motorTotalpower: "电机总功率(k w)",
    motorTotaltorque: "电机总扭矩（N * m）",
    beMotorpower: "前电机最大功率(kw)",
    beMotortotaltorque: "前电机最大扭矩（N * m）",
    numCylinders: "气缸个数",
    fuelForm: "燃料形式",
    supplyMethod: "供油方式",
    headMaterial: "缸盖材料",
    bodyMaterial: "缸体材料",
    environmentalStandards: "环保标准",
    numGears: "变速箱挡位个数",
    typeGear: "变速箱类型",
    beTiresize: "前轮胎规格",
    aftTiresize: "后轮胎规格",
    displacement: "排量（L）",
    upTime: "上市时间",
    speedBox: "变速箱",
    addSpeedone: "官方0-100km/h加速(s)",
    addSpeedfive: "官方0-50km/h加速(s)",
    nedsOilall: "综合油耗（L/100km）",
    lowOilstatus: "最低荷电状态耗油（L/100km）",
    firstWarranty: "首任车主质保政策",
    engineModel: "发动机型号",
    engineLayout: "发动机布局",
    airIntakeform: "进气形式",
    cylinderArrangement: "气缸排列形式",
    numberOfcylinders: "气缸数(个)",
    compressionRatio: "压缩比",
    numOfvalvespercylinder: '每缸气门数(个)',
    valveTrain: "气门机构",
    cylinderDiameter: "缸径 (mm)",
    stroke: "行程 (mm)",
    maximumHorsepower: "最大马力 (Ps)",
    maxKw: "最大功率 (kW)",
    maxRpm: "最大功率转速 (r/min)",
    maxKwbh: "最大扭矩转速(Nm)",
    maxTorquespeed: "最大扭矩转速 (rpm)",
    engineSpecifictechnology: "发动机特有技术",
    fuelNum: "燃料标号",
    oilSupplymethod: "供油方式",
    cylinderHeadmaterial: "岗盖材料",
    cylinderMaterial: "缸体材料",
    maxWaterdeep: "最大涉水深度 (mm)",
    beCapacity: "前电机容量(kWh)",
    fuelTankcapacity: "油箱容积(L)",
    cargoVolume: "行李箱容积(L)",
    numberOftransmissiongears: "挡位个数",
    type: "变速箱类型",
    drivingMethod: "驱动方式",
    fourWheeldriveform: "四驱形式",
    centerDifferentialstructure: "中央差速器结构",

    // 车轮制动
    frontSuspensiontype: "前悬架类型",
    backSuspensiontype: "后悬架类型",
    typeOfassistance: "助力类型",
    vehicleBodystructure: "车体结构",
    frontBraketype: "前制动器类型",
    backBraketype: "后制动器类型",
    parkingBraketype: "驻车制动类型",
    frontTirespecifications: "前轮胎规格",
    backTirespecifications: "后轮胎规格",
    spareTirespecifications: "备胎规格",

    // 内部配置
    steeringWheelmaterial: "方向盘材质",
    wheelPositionadjustment: "方向盘位置调节",
    multifunctionSteeringwheel: "多功能方向盘",
    steeringWheelshifting: "方向盘换挡",
    steeringHot: "方向盘加热",
    steeringMemory: "方向盘记忆",
    computerDisplayscreen: "行车电脑显示屏",
    instrumentPanel: "仪表盘亮度调节",
    instrumentSize: "仪表盘尺寸",
    digitalDisplay: "全液晶仪表盘",
    dashCam: "行车记录仪",
    activeNoisereduction: "主动降噪",
    mobileChargingfunction: "手机无线充电功能",
}


const xxx = {


}